FROM python:3.10.5-slim

WORKDIR /opt/app

RUN pip install poetry
RUN poetry config virtualenvs.create false
RUN pip install pip --upgrade

COPY ./pyproject.toml /opt/app/pyproject.toml
COPY ./poetry.lock /opt/app/poetry.lock

RUN mkdir /opt/app/aligned
RUN poetry install --no-root --extras "redis kafka ollama mlflow lancedb"

COPY aligned /opt/app/aligned
COPY conftest.py /opt/app/conftest.py
COPY test_data /opt/app/test_data
