version: '3'
services:
  psql_app_db:
    image: postgres:latest
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=aligned-test
    ports:
      - 5433:5432

  redis:
    image: 'redis/redis-stack-server:latest'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - 6379:6379
