services:
  psql_app_db:
    image: postgres:latest
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=aligned-test
    ports:
      - 5433:5432

  redis:
    image: 'redis/redis-stack-server:latest'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - 6379:6379

  mlflow-tracker:
    image: ghcr.io/mlflow/mlflow:v2.15.0
    command: "mlflow server --backend-store-uri file:///app/mlflow-server/experiments --artifacts-destination file:///app/mlflow-server/artifacts --host 0.0.0.0 --port 8000"
    volumes:
      - ./mlflow:/app/mlflow-server

  testing:
    build:
      context: .
      dockerfile: Dockerfile.test
    command: "pytest"
    environment:
      - PSQL_DATABASE_TEST=postgresql://postgres:postgres@psql_app_db:5432/aligned-test
      - MLFLOW_TRACKING_URI=http://mlflow-tracker:8000
      - MLFLOW_REGISTRY_URI=http://mlflow-tracker:8000
    volumes:
      - ${PWD}:/opt/app
    depends_on:
      - mlflow-tracker
