name: publish package

on:
  push:
    branches:
      - main

jobs:
  build-and-publish:
    needs: build-and-publish-test
    runs-on: ubuntu-latest
    steps:
      - uses: snok/.github/workflows/publish@main
        with:
          token: ${{ secrets.PYPI_TOKEN }}
          python-version: '3.10.0'
